### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-l2bf0#3]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by rushsh67** [comment]
![Screenshot 2022-09-29 162354](https://user-images.githubusercontent.com/106526534/193014258-dff77915-e2e8-4b78-baab-64335eb7bdff.png)
![Screenshot 2022-09-29 162458](https://user-images.githubusercontent.com/106526534/193014269-5327b913-fb24-4495-bcb2-5b6b8b069f25.png)
changes in Editor.js frontend/src/components/Editor.js
Issue fixed. Thank You
